apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
  namespace: home-assistant
spec:
  selector:
    app: home-assistant
  ports:
  - name: home-assistant-service
    protocol: TCP
    port: 8123
    targetPort: 8123
  type: NodePort
