---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4
      containers:
      - name: home-assistant
        image: homeassistant/home-assistant:2021.12.3
#        ports:
#        - containerPort: 8096
        volumeMounts:
          - name: home-assistant-config
            mountPath: /config
      volumes:
        - name: home-assistant-config
          persistentVolumeClaim:
            claimName: home-assistant-config

